Repository RakambdaOrg/FallingTree, pull requests merged in 2023-06, with the labels that each got.

#540 Automatically set version based on git
  build.gradle
  gradle.properties
  gradle/libs.versions.toml
Labels: type: 🧱 enhancement

#541 Add support for Minecraft 1.20
  forge/src/main/resources/META-INF/mods.toml
  forge/src/main/resources/pack.mcmeta
  gradle/libs.versions.toml
Labels: type: 🧱 enhancement, modloader: Forge, modloader: Fabric

#552 Fabric 1.20.1
  gradle.properties
  gradle/libs.versions.toml
Labels: type: 🧱 enhancement, modloader: Fabric

#553 🔄 synced file(s) with Rakambda/rakambda-github-files
  .github/dependabot.yml
Labels: sync

#554 🔄 synced file(s) with Rakambda/rakambda-github-files
  .github/renovate.json
Labels: sync

#555 Update Forge 1.20.1
  forge/src/main/resources/META-INF/mods.toml
  gradle/libs.versions.toml
Labels: type: 🧱 enhancement, modloader: Forge
