Repository RakambdaOrg/FallingTree, pull requests merged in 2024-06, with the labels that each got.

#698 Fix leaf breaking when speed multiplier is applied
  common/src/main/java/fr/rakambda/fallingtree/common/tree/breaking/FallingAnimationTreeBreakingHandler.java
  common/src/main/java/fr/rakambda/fallingtree/common/tree/breaking/InstantaneousTreeBreakingHandler.java
Labels: type: 🐛 bug, modloader: Forge, modloader: Fabric, modloader: Neoforge

#699 Port to 1.21
  README.md
  common/src/main/java/fr/rakambda/fallingtree/common/FallingTreeCommon.java
  common/src/main/java/fr/rakambda/fallingtree/common/config/IEnchantmentConfiguration.java
  common/src/main/java/fr/rakambda/fallingtree/common/config/real/EnchantmentConfiguration.java
  common/src/main/java/fr/rakambda/fallingtree/common/tree/TreeHandler.java
  common/src/main/java/fr/rakambda/fallingtree/common/wrapper/IItemStack.java
  datapack/data/fallingtree/enchantment/tools/chopper.json
  datapack/data/fallingtree/enchantment/tools/chopper_fall_all_block.json
  datapack/data/fallingtree/enchantment/tools/chopper_fall_block.json
  datapack/data/fallingtree/enchantment/tools/chopper_fall_item.json
  datapack/data/fallingtree/enchantment/tools/chopper_instantaneous.json
  datapack/data/fallingtree/enchantment/tools/chopper_shift_down.json
  datapack/data/fallingtree/tags/enchantment/chopper_all.json
  datapack/data/fallingtree/tags/enchantment/chopper_fall_all_block.json
  datapack/data/fallingtree/tags/enchantment/chopper_fall_block.json
  datapack/data/fallingtree/tags/enchantment/chopper_fall_item.json
  datapack/data/fallingtree/tags/enchantment/chopper_instantaneous.json
  datapack/data/fallingtree/tags/enchantment/chopper_shift_down.json
  datapack/data/fallingtree/tags/enchantment/exclusive_set/chopper.json
  datapack/data/minecraft/tags/enchantment/tradeable.json
  datapack/pack.mcmeta
  fabric/src/client/java/fr/rakambda/fallingtree/fabric/client/cloth/ClothConfigHook.java
  fabric/src/main/java/fr/rakambda/fallingtree/fabric/FallingTree.java
  fabric/src/main/java/fr/rakambda/fallingtree/fabric/FallingTreeUtils.java
  fabric/src/main/java/fr/rakambda/fallingtree/fabric/common/FallingTreeCommonsImpl.java
  fabric/src/main/java/fr/rakambda/fallingtree/fabric/common/wrapper/EnchantmentWrapper.java
  fabric/src/main/java/fr/rakambda/fallingtree/fabric/common/wrapper/ItemStackWrapper.java
  fabric/src/main/java/fr/rakambda/fallingtree/fabric/enchant/ChopperEnchantment.java
  fabric/src/main/java/fr/rakambda/fallingtree/fabric/network/FallingTreeConfigPacket.java
  forge/src/main/java/fr/rakambda/fallingtree/forge/FallingTree.java
  forge/src/main/java/fr/rakambda/fallingtree/forge/FallingTreeUtils.java
  forge/src/main/java/fr/rakambda/fallingtree/forge/common/FallingTreeCommonsImpl.java
  forge/src/main/java/fr/rakambda/fallingtree/forge/common/wrapper/EnchantmentWrapper.java
  forge/src/main/java/fr/rakambda/fallingtree/forge/common/wrapper/ItemStackWrapper.java
  forge/src/main/java/fr/rakambda/fallingtree/forge/enchant/ChopperEnchantment.java
  forge/src/main/java/fr/rakambda/fallingtree/forge/event/FallingTreeEnchantments.java
  forge/src/main/java/fr/rakambda/fallingtree/forge/network/ForgePacketHandler.java
  forge/src/main/resources/META-INF/mods.toml
  forge/src/main/resources/pack.mcmeta
  gradle/libs.versions.toml
  neoforge/src/main/java/fr/rakambda/fallingtree/neoforge/FallingTree.java
  neoforge/src/main/java/fr/rakambda/fallingtree/neoforge/FallingTreeUtils.java
  neoforge/src/main/java/fr/rakambda/fallingtree/neoforge/client/cloth/ClothConfigHook.java
  neoforge/src/main/java/fr/rakambda/fallingtree/neoforge/common/FallingTreeCommonsImpl.java
  neoforge/src/main/java/fr/rakambda/fallingtree/neoforge/common/wrapper/EnchantmentWrapper.java
  neoforge/src/main/java/fr/rakambda/fallingtree/neoforge/common/wrapper/ItemStackWrapper.java
  neoforge/src/main/java/fr/rakambda/fallingtree/neoforge/enchant/ChopperEnchantment.java
  neoforge/src/main/java/fr/rakambda/fallingtree/neoforge/event/FallingTreeBlockBreakEvent.java
  neoforge/src/main/java/fr/rakambda/fallingtree/neoforge/event/FallingTreeEnchantments.java
  neoforge/src/main/java/fr/rakambda/fallingtree/neoforge/network/FallingTreeConfigPacket.java
  neoforge/src/main/resources/META-INF/neoforge.mods.toml
Labels: type: 🧱 enhancement, modloader: Fabric

#706 NeoForge: Fix loading on dedicated if cloth-config is present
  .github/ISSUE_TEMPLATE/2_neoforge-bug-report.yml
  .github/ISSUE_TEMPLATE/3_feature_request.yml
  neoforge/src/main/java/fr/rakambda/fallingtree/neoforge/FallingTree.java
  neoforge/src/main/java/fr/rakambda/fallingtree/neoforge/FallingTreeClient.java
Labels: type: 🐛 bug, modloader: Neoforge

#708 🔄 synced file(s) with RakambdaOrg/rakambda-github-files
  .github/dependabot.yml
  .github/renovate.json
Labels: sync

#710 🔄 synced file(s) with RakambdaOrg/rakambda-github-files
  .github/renovate.json
Labels: sync

#713 🔄 synced file(s) with RakambdaOrg/rakambda-github-files
  .github/dependabot.yml
Labels: sync

#718 NeoForge: Fix ToolActions not found
  gradle/libs.versions.toml
  neoforge/src/main/java/fr/rakambda/fallingtree/neoforge/common/wrapper/ItemStackWrapper.java
Labels: type: 🐛 bug, modloader: Neoforge

#719 Add Vietnamese translations
  common/src/main/resources/assets/fallingtree/lang/vi_vn.json
Labels: type: 🧱 enhancement, modloader: Forge, modloader: Fabric, modloader: Neoforge

#720 Add new option to make all log items spawn at the breaking point
  common/src/main/java/fr/rakambda/fallingtree/common/config/ITreeConfiguration.java
  common/src/main/java/fr/rakambda/fallingtree/common/config/proxy/TreeProxyConfiguration.java
  common/src/main/java/fr/rakambda/fallingtree/common/config/real/TreeConfiguration.java
  common/src/main/java/fr/rakambda/fallingtree/common/tree/breaking/InstantaneousTreeBreakingHandler.java
  common/src/main/java/fr/rakambda/fallingtree/common/tree/breaking/LeafForceBreaker.java
  common/src/main/resources/assets/fallingtree/lang/en_us.json
  fabric/src/client/java/fr/rakambda/fallingtree/fabric/client/cloth/ClothConfigHook.java
  forge/src/main/java/fr/rakambda/fallingtree/forge/client/cloth/ClothConfigHook.java.disabled
  neoforge/src/main/java/fr/rakambda/fallingtree/neoforge/client/cloth/ClothConfigHook.java
Labels: type: 🧱 enhancement, modloader: Forge, modloader: Fabric, modloader: Neoforge
